# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl }:

self: super: {
  "Click" = super.buildPythonPackage rec {
    pname = "Click";
    version = "8.0.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/4a/a8/0b2ced25639fb20cc1c9784de90a8c25f9504a7f18cd8b5397bd61696d7d/click-8.0.4-py3-none-any.whl";
      sha256 = "1cfrsra6bkayc34zcxmx1a69fdaavfhj6c4glfizvaxz7db64yka";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."importlib-metadata"
    ];
  };
  "Deprecated" = super.buildPythonPackage rec {
    pname = "Deprecated";
    version = "1.2.18";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c6/ac0b6c1e2d138f1002bcf799d330bd6d85084fece321e662a14223794041/Deprecated-1.2.18-py2.py3-none-any.whl";
      sha256 = "1v4f05f1pl7ygha63nab47881zq9d8r8x24g84r2ldq0h9w12l5x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."wrapt"
    ];
  };
  "decorator" = super.buildPythonPackage rec {
    pname = "decorator";
    version = "4.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl";
      sha256 = "0q7p11gj5g158gb1igy9cna5ppxf03zkrm2gpr4acjycl3159yj1";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "importlib-metadata" = super.buildPythonPackage rec {
    pname = "importlib-metadata";
    version = "4.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/a1/b153a0a4caf7a7e3f15c2cd56c7702e2cf3d89b1b359d1f1c5e59d68f4ce/importlib_metadata-4.8.3-py3-none-any.whl";
      sha256 = "0pkvblg25ymsl9dzs1ic9pilbk0534j2mi1ks52cln1dbdm5gab5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
      self."zipp"
    ];
  };
  "networkx" = super.buildPythonPackage rec {
    pname = "networkx";
    version = "2.5.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/b7/c7f488101c0bb5e4178f3cde416004280fd40262433496830de8a8c21613/networkx-2.5.1-py3-none-any.whl";
      sha256 = "01jf1jgq3kfqfd61912hx0m8kpsjnj086cn2fk2z92g9sy78ad86";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."decorator"
    ];
  };
  "tabulate" = super.buildPythonPackage rec {
    pname = "tabulate";
    version = "0.8.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/92/4e/e5a13fdb3e6f81ce11893523ff289870c87c8f1f289a7369fb0e9840c3bb/tabulate-0.8.10-py3-none-any.whl";
      sha256 = "1z5lx3hwhlniyard3xhnrhzx73jy1j9fgasnwjwn98ds7m15b80b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "tsplib95" = super.buildPythonPackage rec {
    pname = "tsplib95";
    version = "0.7.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/2b/b1932d3674758ec5f49afa72d4519334a5ac2aac4d96cfd416eb872a1959/tsplib95-0.7.1-py2.py3-none-any.whl";
      sha256 = "114iwmx1a7na0rhqmhjd5raiws5jlmx4g4dl6hhsdaiv567670f4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Click"
      self."Deprecated"
      self."networkx"
      self."tabulate"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/45/6b/44f7f8f1e110027cf88956b59f2fad776cca7e1704396d043f89effd3a0e/typing_extensions-4.1.1-py3-none-any.whl";
      sha256 = "1qlcz26kwq9hnpccn336b7iygp0wfjnv0c4lg785b8drwh7mxj11";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/4c/063a912e20bcef7124e0df97282a8af3ff3e4b603ce84c481d6d7346be0a/wrapt-1.16.0.tar.gz";
      sha256 = "17c9n430v02dyhg5fwskg9zmld1jkzj41b8ygmyd3rvi56ahydsz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "zipp" = super.buildPythonPackage rec {
    pname = "zipp";
    version = "3.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/bd/df/d4a4974a3e3957fd1c1fa3082366d7fff6e428ddb55f074bf64876f8e8ad/zipp-3.6.0-py3-none-any.whl";
      sha256 = "1g20xhzs60l5znrvnv0yfd9k7c1rimirfcr71zjp02laaqhymrcz";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
